<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Selected order is not exists!' => '',
  'The request product does not exists!' => '',
  'Email is incorrect.' => 'E-mail некорректен.',
  'Incorrect recovery link.' => 'Некорректная ссылка для восстановления.',
  'Invalid request. Please do not repeat this request again.' => 'Некорректнаый запрос. Пожалуйста, не повторяйте этот запрос снова.',
  'Node ID #{id_node} not exists.' => 'Раздел #{id_node} не существует.',
  'Product data is empty' => 'Данные о продукции пусты',
  'Root node couldn\'t be moved.' => 'Корневой раздел не может быть перемещен.',
  'The requested node does not exist.' => 'Запрашиваемый раздел не может быть найден.',
  'The requested page does not exist.' => 'Запрашиваемая страница не существует.',
  'There is only one root node.' => 'Может быть только один корневой раздел.',
  'There was error on creating node!' => 'Произошла ошибка при создании раздела!',
  'User\'s email is not exists' => 'Указанный e-mail уже существует',
  'Username is incorrect.' => 'Имя пользователя некорректно.',
);
