<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Approved' => '',
  'Are you sure to delete?' => '',
  'Are you sure?' => '',
  'Article' => '',
  'Basket' => '',
  'Basket is empty' => '',
  'Checkout' => '',
  'Clear basket' => '',
  'Client email' => '',
  'Client information' => '',
  'Client list' => '',
  'Client name' => '',
  'Client phone' => '',
  'Clients' => '',
  'Comment' => '',
  'Completed' => '',
  'Confirm dialog' => '',
  'Count' => '',
  'Delete order' => '',
  'Delivery address' => '',
  'Delivery in the city' => '',
  'Delivery in the city ({delivery} rub.)' => '',
  'Delivery price' => '',
  'Delivery type' => '',
  'Fields with <span class="required">*</span> are required.' => '',
  'Goods' => '',
  'History' => '',
  'Items in basket' => '',
  'List' => '',
  'Manage' => '',
  'New order on {sitename}' => '',
  'Notice email' => '',
  'Notify administrator after order' => '',
  'Notify manager after order' => '',
  'Notify user after order' => '',
  'Order' => '',
  'Order #{id}' => '',
  'Order #{id}: status were changed to `{status}`' => '',
  'Order list' => '',
  'Ordering' => '',
  'Orders' => '',
  'Photo' => '',
  'Pickup' => '',
  'Price' => '',
  'Product' => '',
  'Product list' => '',
  'Products in basket' => '',
  'Refused' => '',
  'Send' => '',
  'Send notice' => '',
  'Sended' => '',
  'Settings' => '',
  'Size' => '',
  'Status' => '',
  'Summa' => '',
  'Thank you made the order on {sitename}!' => '',
  'Time created' => '',
  'Title' => '',
  'Total' => '',
  'Total cost' => '',
  'Total price' => '',
  'Transit' => '',
  'Undefined' => '',
  'Update' => '',
  'Update order' => '',
  'View order' => '',
  'Your order get #{id} number. Watch for changing the status of the order on email' => '',
  'Your order get #{id} number. Watch for changing the status of the order on email or your profile' => '',
  'Your order is accepted and it will be processed in a short time' => '',
);
